### ISSUE TITLE
Replace images with lossless sources

### ISSUE THREAD

**Issue by langri-sha** [nevenagaj/praline#2]
Can you please swoop in and replace all the images and their references with lossless copies? 

I don't know whether the ones being added in have already been compressed. We can do that when we do production builds, but we should best avoid re-compressing them otherwise.

**Comment by nevenagaj** [comment]
Will do that tonightSend from Huawei KIW-L21-------- Original Message --------Subject: [nevenagaj/praline] Replace images with lossless sources (#2)From: Filip Dupanović To: nevenagaj/praline CC: nevenagaj ,Assign Can you please swoop in and replace all the images and their references with lossless copies? 

I don't know whether the ones being added in have already been compressed. We can do that when we do production builds, but we should best avoid re-compressing them otherwise.

**Comment by langri-sha** [comment]
I used hex numerals to label the images. If you have more sensible names, you can use `git mv 00.jpg foobar.jpg` instead.

**Comment by nevenagaj** [comment]
I think I have done the right thing. All imgs have same size and the one named a00 goes only on about page all the others should appear in image slider in background
